name: Build Test

on: [pull_request, push]

jobs:
  testing:
    name: Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

      # Step 1: Assemble debug apk 
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      # TODO: Connect Virtual Device and Run Tests 
      # Step 2: Assemble debug test apk
      # - name: Assemble Debug Test APK
      #   run: ./gradlew connectedDebugAndroidTest